### ISSUE TITLE
There are doubts about the replication of the environment

### ISSUE THREAD

**Issue by ScuLancer** [kyotovision-public/DRMNet#3]
Hello, your paper is very interesting. We want to reproduce the experimental environment, but we encountered some problems. I would like to know if the package version you described in the 'Requirements' directory is correct. For example, we found on the pytorch lighting official website that the Python version compatible with pytorch lighting 1.9 is between ≥ 3.7 and ≤ 3.10, while you provided 3.6. And for the convenience of others reproducing the environment, can you provide a clear requirement. txt or environment. yaml. Thank you very much!

**Comment by ScuLancer** [comment]
Terminal : python scripts/estimate.py --input_img ./data/sample/image.exr --input_normal ./data/sample/normal.npy --input_mask ./data/sample/mask.png
ObsNetDiffusion: Running in eps-prediction mode
DiffusionWrapper has 147.60 M params.
Keeping EMAs of 416.
Using first stage also as cond stage.
Restored from ../autodl-tmp/checkpoints/obsnet.ckpt with 0 missing and 0 unexpected keys
DRMNet: Running in residual-prediction mode


Critical Dr.Jit compiler failure: jit_optix_check(): API error 7990 (OPTIX_ERROR_INTERNAL_ERROR): "Internal error" in /project/src/render/optixdenoiser.cpp:38.
Aborted (core dumped)

**Comment by konishino** [comment]
Latest fix should address these.

**Comment by konishino** [comment]
Closed.
